name: Build and Push latest image

on:
  push:
    # build and push anytime commits are merged to devel
    branches:
      - devel
  schedule:
    # build every 12 hours
    - cron: '0 */12 * * *'

jobs:
  build_and_push_latest:
    runs-on: awx-ee
    name: Build and push latest tag from devel and on new commits
    steps:
      - uses: actions/checkout@v2

      #- uses: actions/setup-python@v2
      #  with:
      #    python-version: "3.9"

      - name: Install dependencies
        run: |
          python3.9 -m pip install --upgrade pip
          python3.9 -m pip install tox

      - name: Build image
        env:
          DOCKER_HOST: 127.0.0.1:2376
          DOCKER_BUILDKIT: 1
          DOCKER_TLS_VERIFY: "false"
        run: |
          tox -e docker -- --tag=ckevi/awx-ee:latest

      - name: Push images
        env:
          DOCKER_HOST: 127.0.0.1:2376
          DOCKER_TLS_VERIFY: "false"
        run: |
         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
         docker push ckevi/awx-ee:latest
